-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 11:06:47 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Клиенты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Клиенты` (
  `id` INT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NOT NULL,
  `инн` VARCHAR(12) NULL,
  `телефон` VARCHAR(20) NULL,
  `адрес` VARCHAR(200) NULL,
  `контактное_лицо` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `инн_UNIQUE` (`инн` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Кампании`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Кампании` (
  `id_кампании` INT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NOT NULL,
  `бюджет` DECIMAL(12,2) NULL,
  `дата_начала` DATE NULL,
  `дата_окончания` DATE NULL,
  `id_клиента` INT NULL,
  PRIMARY KEY (`id_кампании`),
  INDEX `Клиенты_idx` (`id_клиента` ASC) VISIBLE,
  CONSTRAINT `Клиенты`
    FOREIGN KEY (`id_клиента`)
    REFERENCES `mydb`.`Клиенты` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Площадки`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Площадки` (
  `id_площадки` INT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NOT NULL,
  `тип` VARCHAR(50) NULL,
  `стоимость_за_единицу` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_площадки`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Размещения`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Размещения` (
  `id_кампании` INT NOT NULL,
  `id_площадки` VARCHAR(45) NOT NULL,
  `id_Размещения` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_Размещения`),
  CONSTRAINT `Кампании `
    FOREIGN KEY (`id_кампании`)
    REFERENCES `mydb`.`Кампании` (`id_кампании`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Площадки`
    FOREIGN KEY (`id_кампании`)
    REFERENCES `mydb`.`Площадки` (`id_площадки`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Задачи_на_кампанию`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Задачи_на_кампанию` (
  `id_сотрудника` INT NOT NULL,
  `id_кампании` INT NOT NULL,
  `задача` VARCHAR(200) NOT NULL,
  `срок` DATE NULL,
  `статус` VARCHAR(20) NULL,
  PRIMARY KEY (`id_сотрудника`, `id_кампании`),
  INDEX `Кампании_idx` (`id_кампании` ASC) VISIBLE,
  CONSTRAINT `Кампании`
    FOREIGN KEY (`id_кампании`)
    REFERENCES `mydb`.`Задачи_на_кампанию` (`id_кампании`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Сотрудники`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Сотрудники` (
  `Сотрудники` INT NULL AUTO_INCREMENT,
  `фамилия` VARCHAR(50) NOT NULL,
  `имя` VARCHAR(50) NOT NULL,
  `отчество` VARCHAR(50) NULL,
  `должность` VARCHAR(100) NULL,
  `процент_от_сделки` DECIMAL(5,2) NULL,
  PRIMARY KEY (`Сотрудники`),
  CONSTRAINT `Сотрудники`
    FOREIGN KEY (`Сотрудники`)
    REFERENCES `mydb`.`Задачи_на_кампанию` (`id_сотрудника`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
